{
    'name' : 'Ec Extend Account Edi',
    'version' : '16.0',
    'summary': 'Facturacion ELectronica',
    'description': """
    """,
    'category': 'Accounting',
    'author': 'Mauricio Idrovo',
    "company": "Callphone S.A.",
    "website": "https://www.callphoneecuador.com",
    'images' : [],
    'depends' : [
        # 'base_setup',
        # 'account',
        # 'product',
        # 'analytic',
        # 'ec_sri_authorizathions',
        # 'l10n_latam_invoice_document',
        # 'ec_ats',
        # 'mail',
        # 'ec_withholding',
        # 'ec_remision',
        # 'ec_tools',
        # 'ec_account_base',
        # 'smile_amount_in_letters',
        # 'account_invoice_refund_link',
        # 'account_invoice_fixed_discount',
        'ec_account_edi',
        'account',
        'portal',
    ],
    'data': [
        'views/account_portal_template_inh.xml',
    ],
    
    'installable': True,
    'license': 'LGPL-3',
}